export enum ProfileStatus {
	MINE = 'MINE',
	FRIEND = 'FRIEND',
	REQUESTED_BY_ME = 'REQUESTEDBYME',
	REQUESTED_BY_OTHER = 'REQUESTEDBYOTHER',
	BLOCKED_BY_ME = 'BLOCKEDBYME',
	BLOCKED_BY_OTHER = 'BLOCKEDBYOTHER',
	UNKNOWN = 'UNKNOWN', // 탈퇴한 유저. 없는 유저. 내가 누군가에게 차단당한 유저일때
	UNDEFINED = 'UNDEFINED', //유저가 있지만 나랑 아무 관계가 아닐때
}
